[package]
name = "afl-target"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "AFL target for validating the access package"
keywords = ["fuzz", "accumulo-access"]
categories = ["security"]
repository = "https://github.com/willmurnane/access-rs"
readme = "README.md"

[dependencies]
afl = "*"
access = { path = "../access", features = ["debug_simplify"] }

[[bin]]
name = "afl-access-eval"
test = false
doc = false
bench = false
[[bin]]
name = "afl-access-expression"
test = false
doc = false
bench = false
[[bin]]
name = "afl-access-simplify"
test = false
doc = false
bench = false
[[bin]]
name = "afl-access-tokens"
test = false
doc = false
bench = false
