[package]
name = "access"
version = "0.1.0"
edition = "2024"
description = "Accumulo access standard implemented in Rust"
license = "Apache-2.0"
repository = "https://github.com/willmurnane/access-rs"
readme = "README.md"
keywords = ["accumulo-access"]
categories = ["authentication", "security"]

[features]
debug_simplify = ["tracing", "tracing-subscriber"]

[dependencies]
ariadne = "0.6"
chumsky = "0.12"
serde = "1.0"
tracing = { version = "0.1.43", optional = true }
tracing-subscriber = { version = "0.3.22", optional = true }

[dev-dependencies]
criterion = "0.8"
serde_test = "1.0"
j4rs = "0.24.0"

[[bench]]
name = "access"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }
