[package]
name = "access"
version = "0.1.0"
edition = "2024"
description = "Accumulo access standard implemented in Rust"
license = "Apache-2.0"
repository = "https://github.com/willmurnane/access-rs"
readme = "README.md"
keywords = ["accumulo-access"]
categories = ["authentication", "security"]

[dependencies]
ariadne = "0.5"
chumsky = "0.11"
serde = "1.0"

[dev-dependencies]
criterion = "0.7"
serde_test = "1.0"

[[bench]]
name = "access"
harness = false
